Written by: Michael Brown

In [21]:
import numpy as np

# Describing a Circuit with Unitary Matrix
**Exam review q2** Describe "Action" of the circit with a unitary circuit matrix:

- Action: $ C_{21} C_{12} C_{21} $

In [28]:
CNOT2_1 = np.array([[1,0,0,0], [0,0,0,1], [0,0,1,0], [0,1,0,0]])
print("CNOT with the second bit as a control acting on the first: \n", CNOT2_1)
CNOT1_2 = np.array([[1,0,0,0], [0,1,0,0], [0,0,0,1], [0,0,1,0]])
print("CNOT with the first bit as a control bit acting on the second: \n", CNOT1_2)


CNOT with the second bit as a control acting on the first: 
 [[1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]
CNOT with the first bit as a control bit acting on the second: 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]


In [29]:
result = np.dot(CNOT1_2, CNOT2_1)


In [30]:
result = np.dot(result, CNOT1_2)

In [31]:
print(result)

[[1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]]


In [32]:
H = np.array([[1,1], [1,-1]])
H

array([[ 1,  1],
       [ 1, -1]])

## Building $H_2 = H \otimes H$

In [19]:
H2 = np.kron(H,H)
print(H2)

[[ 1  1  1  1]
 [ 1 -1  1 -1]
 [ 1  1 -1 -1]
 [ 1 -1 -1  1]]


In [20]:
H2 = np.kron(H,H)
print(H2)

[[ 1  1  1  1]
 [ 1 -1  1 -1]
 [ 1  1 -1 -1]
 [ 1 -1 -1  1]]
