Written by: Michael Brown

- **Rembember to use kronecker product for ket-ket or bra-bra operations** 
  - Dot product for bra-ket
  - Outer product for ket-bra


In [83]:
import numpy as np

## Inner product <a|b>
Given two kets:
- |a> = |+> 
- |b> = |->

Find <a|b> or just <+|->

### State |a> = |+> =

In [84]:
coef = 1/np.sqrt(2)
plus_ket = coef*np.array([[1,1]]).transpose()
plus_ket

array([[0.70710678],
       [0.70710678]])

**Take to conjugate transpose** to switch from ket |a> to bra <a|
- Won't do anything for real numbers

In [85]:
def ketToBra(ket):
    return ket.conjugate().transpose()

plus_bra = ketToBra(plus_ket)
plus_bra

array([[0.70710678, 0.70710678]])

### State |b> = |-> =

In [86]:
coef = 1/np.sqrt(2)
minus_ket = coef*np.array([[1,-1]]).transpose()
minus_ket

array([[ 0.70710678],
       [-0.70710678]])

### Now taking inner product <a|b>

In [87]:
inner_product = np.dot(plus_bra, minus_ket)
inner_product

array([[0.]])

# Another Example
number 4iii on review

First creating |$\phi_0$>

In [88]:
zero_ket = np.array([[1,0]]).transpose()
zero_ket

array([[1],
       [0]])

Combining two kets, Kronecker product

In [89]:
zero2_ket = np.kron(zero_ket, zero_ket)
zero2_ket

array([[1],
       [0],
       [0],
       [0]])

In [90]:
one_ket = np.array([[0,1]]).transpose()
one_ket

array([[0],
       [1]])

In [91]:
one2_ket = np.kron(one_ket, one_ket)
one2_ket

array([[0],
       [0],
       [0],
       [1]])

In [92]:
coef = 1/np.sqrt(2)
phi_0_ket = coef*(zero2_ket + one2_ket)
phi_0_ket

array([[0.70710678],
       [0.        ],
       [0.        ],
       [0.70710678]])

In [93]:
plus_0_bra = np.kron(ketToBra(plus_ket), ketToBra(zero_ket))

In [94]:
result = np.dot(plus_0_bra, phi_0_ket)
result

array([[0.5]])

## Another Example
number 4 iv on review

Constructing |$\phi_1$>, using `zero_ket` and `one_ket` from above

In [95]:
coef = 1/np.sqrt(2)
phi_1_ket = coef*(np.kron(zero_ket, one_ket) + np.kron(one_ket, zero_ket))
phi_1_ket

array([[0.        ],
       [0.70710678],
       [0.70710678],
       [0.        ]])

In [98]:
np.dot(ketToBra(phi_1_ket), phi_0_ket)

array([[0.]])

## Last Example
number 4 v on review